# Basic
ClusterName=slurm-cluster
ControlMachine=slurmctld
AuthType=auth/munge
SlurmUser=slurm
SlurmdUser=root
SlurmctldPort=6817
SlurmdPort=6818
StateSaveLocation=/var/spool/slurm
SlurmdSpoolDir=/var/spool/slurm
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmdPidFile=/var/run/slurm/slurmd.pid
ProctrackType=proctrack/cgroup
ReturnToService=2
SwitchType=switch/none
MpiDefault=none
# Prevent the MailProg error:
MailProg=/bin/false

# Accounting via slurmdbd (NOT direct MySQL)
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=slurmdbd
# optional: AccountingStoragePort=6819
JobCompType=jobcomp/none
JobAcctGatherType=jobacct_gather/linux

# Nodes/partition
NodeName=c[1-2] CPUs=2 RealMemory=2000 Sockets=1 CoresPerSocket=2 ThreadsPerCore=1 State=UNKNOWN
PartitionName=normal Nodes=c[1-2] Default=YES MaxTime=INFINITE State=UP
